CREATE TABLE IMAGE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA LONGTEXT NOT NULL CHARACTER SET utf16 COLLATE utf16_general_ci
);

CREATE TABLE AUDIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA LONGTEXT NOT NULL CHARACTER SET utf16 COLLATE utf16_general_ci
);